set (CMAKE_SYSTEM_PROCESSOR "microblaze" CACHE STRING "")
set (MACHINE "microblaze_generic")
set (CROSS_PREFIX "mb-" CACHE STRING "")
set (CMAKE_C_FLAGS " -mlittle-endian -mxl-soft-mul -mcpu=v10.0  -mlittle-endian -ffunction-sections -fdata-sections -Wall -Wextra -I/home/dinne/yocto_zedboard/vivado_linux_zynq/vivado_project/vivado_linux_zynq.sdk/mb_bsp/microblaze_0/include" CACHE STRING "")
set (CMAKE_SYSTEM_NAME "Generic" CACHE STRING "")
include (CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER ("${CROSS_PREFIX}gcc" GNU)
CMAKE_FORCE_CXX_COMPILER ("${CROSS_PREFIX}g++" GNU)
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER CACHE STRING "")
